apiVersion: v1
kind: Service
metadata:
  name:: chart-fullname
  labels:: common-labels()
spec:
  type:: Values.service.type
  ports:
  - port:: Values.service.port
    targetPort: http
    protocol: TCP
    name: http
  selector:: selectorLabels()
