# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in yamlscript.gemspec
gemspec

gem "rake", "~> 13.0"
gem "minitest", "~> 5.20.0"
gem "mutex_m", "~> 0.3"
