# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

Rake::Task["release:guard_clean"].clear
Rake::Task["release:source_control_push"].clear

# Disable tagging for `rake release`
namespace :release do
  task :commit do
    puts "Overriding commit task"
  end
  task :guard_clean do
    puts "Overriding guard_clean task"
  end
  task :tag do
    puts "Overriding tag task"
  end
  task :push do
    puts "Overriding push task"
  end
  task :source_control_push do
    puts "Overriding source_control_push task"
  end
end

Minitest::TestTask.create(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.warning = false
  t.test_globs = ["test/**/*_test.rb"]
end

task :default => :test
