;; Copyright 2023-2026 Ingy dot Net
;; This code is licensed under MIT license (See License for details)

;; Glojure implementation of the public clojure.math surface.

(ns clojure.math)

(def E Math/E)
(def PI Math/PI)

(defn sin [x] (Math/sin x))
(defn cos [x] (Math/cos x))
(defn tan [x] (Math/tan x))
(defn asin [x] (Math/asin x))
(defn acos [x] (Math/acos x))
(defn atan [x] (Math/atan x))
(defn to-radians [x] (Math/toRadians x))
(defn to-degrees [x] (Math/toDegrees x))
(defn exp [x] (Math/exp x))
(defn log [x] (Math/log x))
(defn log10 [x] (Math/log10 x))
(defn sqrt [x] (Math/sqrt x))
(defn cbrt [x] (Math/cbrt x))
(defn IEEE-remainder [x y] (Math/IEEEremainder x y))
(defn ceil [x] (Math/ceil x))
(defn floor [x] (Math/floor x))
(defn rint [x] (Math/rint x))
(defn atan2 [y x] (Math/atan2 y x))
(defn pow [x y] (Math/pow x y))
(defn round [x] (Math/round x))
(defn random [] (Math/random))
(defn add-exact [x y] (Math/addExact x y))
(defn subtract-exact [x y] (Math/subtractExact x y))
(defn multiply-exact [x y] (Math/multiplyExact x y))
(defn increment-exact [x] (Math/incrementExact x))
(defn decrement-exact [x] (Math/decrementExact x))
(defn negate-exact [x] (Math/negateExact x))
(defn floor-div [x y] (Math/floorDiv x y))
(defn floor-mod [x y] (Math/floorMod x y))
(defn ulp [x] (Math/ulp x))
(defn signum [x] (Math/signum x))
(defn sinh [x] (Math/sinh x))
(defn cosh [x] (Math/cosh x))
(defn tanh [x] (Math/tanh x))
(defn hypot [x y] (Math/hypot x y))
(defn expm1 [x] (Math/expm1 x))
(defn log1p [x] (Math/log1p x))
(defn copy-sign [magnitude sign] (Math/copySign magnitude sign))
(defn get-exponent [x] (Math/getExponent x))
(defn next-after [start direction] (Math/nextAfter start direction))
(defn next-up [x] (Math/nextUp x))
(defn next-down [x] (Math/nextDown x))
(defn scalb [x scale] (Math/scalb x scale))
