#!/usr/bin/env bash

set -euo pipefail

ydir=.helm-ys
renderer=$ydir/helm-ys-run
raw=https://raw.githubusercontent.com/ingydotnet/helm-ys/refs/heads/main/helm-ys-setup

main() (
[[ -e Chart.yaml ]] ||
  die "Not in a helm chart directory"

  if ! [[ -d $ydir && -f $renderer ]]; then
    curl -s $raw | $(BASH)
  fi

  echo "$renderer"
)

die() { echo "$*"; exit 1; }

main "$@"
