#!/usr/bin/env bash

set -e -u -o pipefail
set -x

branch=main
branch=install
export download=ys

url=https://raw.githubusercontent.com/yaml/yamlscript/$branch/common/install

main() (
  command -v curl >/dev/null ||
    die "curl not found"

  set -x

  install=$(mktemp)
  ls -l "$install"

  curl -s -L -o "$install" "$url"

  bash "$install"

  if [[ $? -eq 0 ]]; then
    rm -f "$install"
  fi
)

die() (
  printf '%s\n' "$@" >&2
  exit 1
)

main "$@"
