#!/usr/bin/env bash

set -euo pipefail

main() {
  local YAMLSCRIPT_VERSION=0.1.71

  VERSION=${YS_VERSION:-$YAMLSCRIPT_VERSION}

  [[ -d /tmp && -w /tmp ]] ||
    die "Can't write to /tmp/"

  local prefix=/tmp/yamlscript-auto-install
  mkdir -p "$prefix"
  [[ -d $prefix && -w $prefix ]] ||
    die "Can't write to '$prefix/'"

  local bin=$prefix/bin
  [[ -e $bin ]] && ! [[ -d $bin && -w $bin ]] &&
    die "Can't write to '$bin/'"

  export PATH=$bin:$PATH

  assert-ys

  local file=${BASH_SOURCE[${#BASH_SOURCE[*]}-1]}
  [[ -f $file ]] ||
    die "Can't find '$file'"

  [[ $# -gt 0 ]] && [[ ${*:$#} == ':' ]] &&
    set -- "${@:1:$#-1}"

  exec ys-0 "$file" "$@"
}

assert-ys() {
  [[ -f $bin/ys-0 && -x $bin/ys-0 ]] && return

  [[ $(command -v curl) ]] ||
    die "'curl' command is required but not found"

  curl -s https://yamlscript.org/install |
    BIN=1 PREFIX=$prefix VERSION=$VERSION bash &> /dev/tty

  # XXX - Temporary testing hack
  [[ -e ~/src/yamlscript/ys/bin/ys ]] &&
    cp ~/src/yamlscript/ys/bin/ys* $bin/

  [[ $(command -v ys-0) == $bin/ys-0 ]] ||
    die "Something went wrong"
}

die() {
  echo "$*" >&2
  exit 1
}

main "$@"
