name = "yamlscript"
description = "YAMLScript language binding for Ada"
version = "0.2.28"
licenses = "MIT"
authors = ["YAMLScript Contributors"]
maintainers = ["YAMLScript Contributors <ingy@ingy.net>"]
maintainers-logins = ["ingydotnet"]
project-files = ["ada/yamlscript.gpr"]
tags = ["yaml", "yamlscript", "loader"]
website = "https://yamlscript.org"

[[depends-on]]
gnat = ">=16"
