/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rapidyaml_Rapidyaml */

#ifndef _Included_org_rapidyaml_Rapidyaml
#define _Included_org_rapidyaml_Rapidyaml
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rapidyaml_Rapidyaml
 * Method:    ysparse_timing_set
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_rapidyaml_Rapidyaml_ysparse_1timing_1set
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_rapidyaml_Rapidyaml
 * Method:    ysparse_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rapidyaml_Rapidyaml_ysparse_1init
  (JNIEnv *, jobject);

/*
 * Class:     org_rapidyaml_Rapidyaml
 * Method:    ysparse_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rapidyaml_Rapidyaml_ysparse_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rapidyaml_Rapidyaml
 * Method:    ysparse_parse
 * Signature: (JLjava/lang/String;[BI[II)I
 */
JNIEXPORT jint JNICALL Java_org_rapidyaml_Rapidyaml_ysparse_1parse
  (JNIEnv *, jobject, jlong, jstring, jbyteArray, jint, jintArray, jint);

/*
 * Class:     org_rapidyaml_Rapidyaml
 * Method:    ysparse_parse_buf
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;ILjava/nio/IntBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_rapidyaml_Rapidyaml_ysparse_1parse_1buf
  (JNIEnv *, jobject, jlong, jstring, jobject, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
