/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rapidyaml_Rapidyaml */

#ifndef _Included_org_rapidyaml_Rapidyaml
#define _Included_org_rapidyaml_Rapidyaml
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rapidyaml_Rapidyaml
 * Method:    ys2edn_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rapidyaml_Rapidyaml_ys2edn_1init
  (JNIEnv *, jobject);

/*
 * Class:     org_rapidyaml_Rapidyaml
 * Method:    ys2edn_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rapidyaml_Rapidyaml_ys2edn_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rapidyaml_Rapidyaml
 * Method:    ys2edn_parse
 * Signature: (JLjava/lang/String;[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_rapidyaml_Rapidyaml_ys2edn_1parse
  (JNIEnv *, jobject, jlong, jstring, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_rapidyaml_Rapidyaml
 * Method:    ys2edn_retry_get
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_rapidyaml_Rapidyaml_ys2edn_1retry_1get
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
