!YS-v0:

:use loader:
  :url "github:yaml/yamlscript/devops-416/loader.ys@talk" :all
vars =: load-vars()

database:
  host:: vars.db-host
  port:: vars.db-port
  user:: vars.db-user
  password:: vars.db-password












