#!/bin/sh

PERL=$(which perl)

if ( which perl && which ys-yamlscript.pl ) >/dev/null; then
  exec "/home/ingy/perl5/perlbrew/perls/perl-5.28.0/bin/perl" "$(which ys-yamlscript.pl)" "$@"
else
  echo "No YAMLScript interpreter found"
  exit 1
fi
