include ../common/base.mk

include $(MAKES)/zild.mk
include $(MAKES)/shell.mk

#------------------------------------------------------------------------------
test-cpan:: disttest

clean::
	$(RM) -r cpan Alien-YAMLScript*

build-doc::
