#!/usr/bin/env bash

lang=go

source "${YAMLSCRIPT_ROOT?}/util/release-repo.bash"

update() (
  cp "$root/License" "$repo_dir/LICENSE"

  (
    cd "$from_dir" || exit
    cp \
      ReadMe.md \
      go.mod \
      go.sum \
      yamlscript.go \
      "$repo_dir"
  )

  perl -pi -e 's{yamlscript/go}{yamlscript-go}' \
    "$repo_dir/go.mod"
)

main "$@"
