#!/usr/bin/env bash

set -euo pipefail

main() (
  setup "$@"

  for file in "${files[@]}"; do
    update-file "$file" "$old" "$new"
  done

  echo
  echo "Done. Review changes:"
  git diff --minimal |
    grep -E '^(diff|-|\+)' |
    grep -Ev '^(---|\+\+\+)'
)

update-file() {
  local file=$1 old=$2 new=$3

  perl -i -pe "s/(yamlscript.*)$old(?=[\ \-\"\']|$)/\${1}$new/gim" "$file"
  perl -i -pe "s/^(version: )$old$/\${1}$new/m" "$file"
  perl -i -pe "s/^(VERSION=)$old$/\${1}$new/m" "$file"

  if git diff --quiet "$file"; then
    echo "* No changes to $file"
  else
    echo "* Updated $file"
  fi
}

setup() {
  old=${1-} new=${2-}
  [[ $old && $new ]] ||
    die "usage: $0 <old-version> <new-version>"
  [[ $old =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
    die "Error: old version must be of the form #.#.#"
  [[ $new =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
    die "Error: new version must be of the form #.#.#"
  [[ $old != "$new" ]] ||
    die "Error: old and new must be different"
  old=${1//./\\.}

  files=(
    Meta
    .profile
    common/install
    common/project.clj
    core/project.clj
    libyamlscript/project.clj
    ys/deps.edn
    ys/project.clj
    ys/share/ys-0.bash
    ys/src/yamlscript/cli.clj
  )
}

die() {
  echo "$*" >&2
  exit 1
}

[[ $0 != "${BASH_SOURCE[0]}" ]] || main "$@"
