# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: YAMLScript
site_url: https://www.yamlscript.org
site_author: Ingy döt Net
site_description: Code is Data — Program in YAML
repo_url: https://github.com/yaml/yamlscript
edit_uri: https://github.com/yaml/yamlscript/tree/documentation/www/src
docs_dir: src
copyright: Copyright 2022-2024
theme:
  name: material
  logo: images/yamlscript-logo.svg
  favicon: images/favicon.ico
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
strict: false
dev_addr: 0.0.0.0:8000
plugins:
- search
- awesome-pages
