#!/usr/bin/env bash

set -e -u -o pipefail

VERSION=0.1.28

main() (
  setup "$@"

  dir=$(mktemp -d)

  curl -sL -o "$dir/download.tar.xz" "$download_url"

  tar -xf "$dir/download.tar.xz" -C "$dir"

  (
    cd "$dir" || exit

    make -C $download-* install
  )

  rm -fr "$dir"
)


setup() {
  vers=$VERSION
  [[ $download ]] ||
    die "Error: Var 'download' not set. Must be 'ys' or 'libyamlscript'"

  if [[ $OSTYPE == *darwin* ]]; then
    os=macos
  elif [[ $OSTYPE == *linux* ]]; then
    os=linux
  else
    die "Unknown OS type: $OSTYPE"
  fi

  if [[ $MACHTYPE == *x86_64* ]]; then
    arch=x64
  elif [[ $MACHTYPE == *arm64* || $MACHTYPE == *aarch64* ]]; then
    arch=aarch64
  else
    die "Unknown machine type: $MACHTYPE"
  fi

  download_url=https://github.com/yaml/yamlscript/releases/download/
  download_url+=$vers/$download-$vers-$os-$arch.tar.xz

  if [[ $PREFIX && $PREFIX != /* ]]; then
    export PREFIX=$PWD/$PREFIX
  fi
}

die() {
  printf '%s\n' "$@" >&2
  exit 1
}

main "$@"
