#!/usr/bin/env bash

[[ ${X-} == 1 ]] && set -x

set -e -u -o pipefail

branch=${YS_BRANCH:-main}
export download=libyamlscript

url=https://raw.githubusercontent.com/yaml/yamlscript/$branch/common/install

main() (
  command -v curl >/dev/null ||
    die "curl not found"

  install=$(mktemp)

  curl -sL "$url" > "$install"

  bash "$install"

  if [[ $? -eq 0 ]]; then
    rm -f "$install"
  fi
)

die() (
  printf '%s\n' "$@" >&2
  exit 1
)

main "$@"
