#!/usr/bin/env bash

[[ ${DEBUG-} == 1 ]] && set -x

set -e -u -o pipefail

LIBYAMLSCRIPT_VERSION=0.1.37
VERSION=${VERSION:-$LIBYAMLSCRIPT_VERSION}

main() (
  setup "$@"

  if ! [[ ${BIN-} || ${LIB-} ]]; then
    install ys
    install libyamlscript
  elif [[ ${BIN-} ]]; then
    install ys
  elif [[ ${LIB-} ]]; then
    install libyamlscript
  fi
)

install() (
  name=$1

  url+=/$vers/$name-$vers-$os-$arch.tar.xz

  curl -s -S -L -o "$dir/download.tar.xz" "$url"

  release_dir=$dir/$name
  mkdir -- "$release_dir"
  tar -xf "$dir/download.tar.xz" -C "$release_dir"

  (
    CDPATH='' cd -- "$release_dir" || exit

    make -s --no-print-directory -C "$name"-* install
  )
)

setup() {
  vers=$VERSION

  if [[ $OSTYPE == *darwin* ]]; then
    os=macos
  elif [[ $OSTYPE == *linux* ]]; then
    os=linux
  else
    die "Unknown OS type: $OSTYPE"
  fi

  if [[ $MACHTYPE == *x86_64* ]]; then
    arch=x64
  elif [[ $MACHTYPE == *arm64* || $MACHTYPE == *aarch64* ]]; then
    arch=aarch64
  else
    die "Unknown machine type: $MACHTYPE"
  fi

  url=https://github.com/yaml/yamlscript/releases/download/

  if [[ ${PREFIX-} && $PREFIX != /* ]]; then
    export PREFIX=$PWD/$PREFIX
  fi

  unset -v dir
  
  trap '[[ ${dir-} ]] && rm -fr -- "$dir"' EXIT

  dir=$(mktemp -d)
}

die() {
  printf '%s\n' "$@" >&2
  exit 1
}

main "$@"
