#!/usr/bin/env bash

cat <<...

--------------------------------------------------------------------------------
ERROR: 'install-ys' has been renamed to 'install'.

Use:

  curl https://yamlscript.org/install | BIN=1 bash
--------------------------------------------------------------------------------

...
