// Generated by CoffeeScript 2.6.1
(function() {
  var yamlscript;

  require('yaml');

  yamlscript = (function() {
    class yamlscript {};

    yamlscript.prototype.version = '0.0.1';

    return yamlscript;

  }).call(this);

}).call(this);
