- Contribute: contribute.md
- Discuss YS: https://github.com/yaml/yamlscript/discussions
- Matrix Chat: https://matrix.to/#/#chat-yamlscript:yaml.io
- Slack Chat: https://matrix.to/#/#chat-yamlscript:yaml.io
