- documentation/index.md
- TL;DR Topics:

  - YAMLScript by Example: doc/examples.md
  - Learn YAMLScript (for free) at Exercism: https://exercism.org/tracks/yamlscript.md
  - YAMLScript Cheat Sheet: doc/cheat.md


- Getting Started:

  - Introducing YAMLScript: doc/intro.md
  - The `ys` Command: doc/ys.md
  - YAMLScript Loader Libraries: doc/loaders.md
  - Installing YAMLScript: doc/install.md


- Tutorials:

  - Clojure to YAMLScript: doc/clj-to-ys.md


- Language Basics:

  - YAML Basics: doc/yaml.md
  - Clojure Basics: doc/clojure.md
  - YeS Expressions: doc/yes.md
  - YAMLScript Modes: doc/modes.md
  - Control Flow: doc/control.md
  - Operators: doc/operators.md
  - Dot Chaining: doc/chain.md
  - Unit Testing: doc/ys-taptest.md


- Functions and Libraries:

  - Core Library Essentials: doc/core.md
  - YAMLScript Standard Library: doc/ys-std.md
  - Builtin Internal Libraries: doc/ys-libs.md


- Advanced Topics:

  - Compiling YAMLScript to Binary: doc/binary.md
  - Self Installation Scripts: doc/run-ys.md










# - Getting Started:
#   - Install YS: doc/install.md
# 
# 
# - TL;DR Topics:
#   - YAMLScript by Example (**Recommended**): doc/examples.md
#   - Learn YAMLScript (for free) at Exercism:
#       https://exercism.org/tracks/yamlscript
#   - YAMLScript Cheat Sheet: doc/cheat.md
# 
# 
# - Getting Started:
# # * [Learn YAMLScript in 15 Minutes](doc/learn)
#   - Introducing YAMLScript: doc/intro.md
#   - The `ys` Command: doc/ys.md
#   - YAMLScript Loader Libraries: doc/loaders.md
#   - Installing YAMLScript: doc/install.md
# 
# 
# - Tutorials:
#   - Clojure to YAMLScript: doc/clj-to-ys.md
# 
# 
# - Language Basics:
# 
#   - YAML Basics: doc/yaml.md
#   - Clojure Basics: doc/clojure.md
#   - YeS Expressions: doc/yes.md
#   - YAMLScript Modes: doc/modes.md
#   - Control Flow: doc/control.md
#   - Operators: doc/operators.md
#   - Dot Chaining: doc/chain.md
#   - Unit Testing: doc/ys-taptest.md
# 
# # * [Syntax Overview](doc/syntax) - under construction
# # * [Variables and Functions](doc/define)
# # * [Common Functions](doc/common) - coming soon
# # * [Data Referencing](doc/referencing) - coming soon
# 
# 
# - Functions and Libraries:
# - YS Standard Library: doc/ys-std.md
#   - Core Library Essentials: doc/core.md
#   - YS Standard Library: doc/ys-std.md
#   - Builtin Internal Libraries: doc/ys-libs.md
# 
# # * [Using External Libraries](doc/ext-libs) - coming soon
# 
# 
# - Advanced Topics:
#   - Compiling YAMLScript to Binary: doc/binary.md
#   - Self Installation Scripts: doc/run-ys.md
# 
# # - Tutorials:
# #   - Writing YS Modules: doc/modules.md
# 
# # - Overview: docs/overview.md
# # - Configuration: docs/configuration.md
# # - Usage: docs/usage.md
# # - Examples: docs/examples.md
# # - Contributing: docs/contributing.md
# # - Changelog: docs/changelog.md
# 
# # - Gallery:
# #   - YS for YAML Users: doc/yaml.md
# #   - YS on Exercism: doc/exercism.md
# #   - YS on Rosetta Code: doc/rosetta.md
# #   - YS for Jsonnet Users: doc/jsonnet.md
# #   - YS for Cue Users: doc/cue.md
# #   - YS for HCL Users: doc/hcl.md
# #   - YS for Jinja2 Users: doc/jinja2.md
# #   - YS for Python Programmers: doc/python.md
# #   - YS for Clojure Programmers: doc/clojure.md
# 
