!YS-v0:

# See: https://github.com/squidfunk/mkdocs-material/discussions/3406
# for info on template overrides.
# Template source:
#   https://github.com/squidfunk/mkdocs-material/tree/master/material/templates

name: material

custom_dir: theme

# * For dark themed code blocks
#   See: https://github.com/squidfunk/mkdocs-material/issues/768

features:
- content.action.edit
- content.action.view
- content.code.copy
- header.autohide
- navigation.expand
- navigation.footer
- navigation.indexes
- navigation.tabs

# - navigation.instant  # For single page application

logo-image =: 'image/yamlscript-logo.svg'

logo:: logo-image
favicon:: logo-image

palette:
- scheme: default
  primary: custom
  toggle:
    icon: material/weather-night
    name: Switch to dark mode

- scheme: slate
  primary: custom
  toggle:
    icon: material/weather-sunny
    name: Switch to light mode

icon:
  edit: material/pencil
  view: material/eye
  talk: material/chat-question
  admonition:
    abstract: fontawesome/solid/book
    bug: fontawesome/solid/robot
    danger: fontawesome/solid/skull
    example: fontawesome/solid/flask
    failure: fontawesome/solid/bomb
    info: fontawesome/solid/circle-info
    note: octicons/note-16
    question: fontawesome/solid/circle-question
    quote: fontawesome/solid/quote-left
    success: fontawesome/solid/check
    tip: fontawesome/solid/bullhorn
    warning: fontawesome/solid/triangle-exclamation
