- use/index.md

- doc/query.md

- DevOps:
  - doc/helmys.md

- CI/CD:
  - cicd.md
  - gha.md
  - circleci.md

# - Static Site Generators:
#   - This site

- hacks.md

# - hacks/index.md:
#   - yamllm.md
#   - mdys.md
#   - siteys.md
#   - sbs.md
#   - gist.md
#   - gmail.md
