- use/index.md

- doc/query.md

- DevOps:
  - helmys.md

- CI/CD:
  - cicd.md
  - gha.md
  - circleci.md

# - Static Site Generators:
#   - This site

- Hacks:
  - hacks.md
  - gist.md
  - yamllm.md
# - sbs.md

# - hacks/index.md:
#   - yamllm.md
#   - mdys.md
#   - siteys.md
#   - sbs.md
#   - gist.md
#   - gmail.md
