<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.yamlscript</groupId>
  <artifactId>scala-yamlscript</artifactId>
  <version>0.2.30</version>
  <packaging>jar</packaging>

  <name>scala-yamlscript</name>
  <description>YAMLScript language binding for Scala</description>
  <url>https://yamlscript.org</url>

  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/license/mit/</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>ingydotnet</id>
      <name>Ingy dot Net</name>
      <email>ingy@ingy.net</email>
      <url>https://github.com/ingydotnet</url>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:https://github.com/yaml/yamlscript.git</connection>
    <developerConnection>
      scm:git:ssh://git@github.com/yaml/yamlscript.git
    </developerConnection>
    <url>https://github.com/yaml/yamlscript</url>
    <tag>0.2.30</tag>
  </scm>

  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <scala.version>3.7.3</scala.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala3-library_3</artifactId>
      <version>${scala.version}</version>
    </dependency>
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna</artifactId>
      <version>5.14.0</version>
    </dependency>
    <dependency>
      <groupId>com.lihaoyi</groupId>
      <artifactId>upickle_3</artifactId>
      <version>4.2.1</version>
    </dependency>
  </dependencies>

  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>4.9.7</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
