(say (_+ 2 2))
(say (_+ "two" "two"))
(say (_+ [1 2] [3 4]))
(say (_* 3 3))
(say (_* 3 "three"))
(say (_* "three" 3))
(say (_* (__ (/ 4 4) '(inc) '(str)) 4))
(say (rng 10 1))
(say (rem -23 7))
(say (mod -23 7))
(say (=-- "foo" #".*(oo)"))
(+++ nil)
