include ../common/base.mk
include $(COMMON)/binding.mk
include $(COMMON)/clojure.mk

#------------------------------------------------------------------------------

test install:: $(LEIN) $(YAMLSCRIPT_JAVA_INSTALLED)
	$< $@
