name: rapidyaml

defaults:
  run:
    shell: bash -xeo pipefail {0}
'on':
  workflow_dispatch: null
  push:
    branches:
    - main
  pull_request:

jobs:

  # check that the spec'ed version of rapidyaml passes its own tests
  ryml:
    runs-on: ubuntu-24.04
    if: always()
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
        - bt: Debug
        - bt: Release
    steps:
    - name: checkout (action)
      uses: actions/checkout@v4
      with: {submodules: recursive, fetch-depth: 0} # use fetch-depth to ensure all tags are fetched
    - name: checkout rapidyaml
      run: |
        cd rapidyaml/native
        make rapidyaml
    - name: configure
      run: |
        cd rapidyaml/native/rapidyaml
        cmake -B build -D CMAKE_BUILD_TYPE=${{matrix.bt}} -D RYML_BUILD_TESTS=ON
    - name: build
      run: |
        cd rapidyaml/native/rapidyaml
        cmake --build build --target ryml-test-build --parallel --verbose
    - name: run tests
      run: |
        cd rapidyaml/native/rapidyaml
        cmake --build build --target ryml-test-run

  # run the c++ tests, also in Debug to test with assertions
  cpp:
    runs-on: ubuntu-24.04
    if: always()
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
        - bt: Debug
        - bt: Release
    steps:
    - name: checkout (action)
      uses: actions/checkout@v4
      with: {submodules: recursive, fetch-depth: 0} # use fetch-depth to ensure all tags are fetched
    - name: check jni header up to date
      run: |
        make -C rapidyaml/native -B jni jnicheck
    - name: get rapidyaml
      run: |
        make -C rapidyaml/native rapidyaml
    - name: c++ tests, no timing ---------------------------------------------------
      run: echo
    - name: cfg c++ tests, no timing
      run: |
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        RAPIDYAML_TIMED=0 \
        make -C rapidyaml/native cfg
    - name: build c++ tests, no timing
      run: |
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        RAPIDYAML_TIMED=0 \
        make -C rapidyaml/native build
    - name: run c++ tests, no timing
      run: |
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        RAPIDYAML_TIMED=0 \
        make -C rapidyaml/native test
    - name: c++ tests, with timing ---------------------------------------------------
      run: echo
    - name: cfg c++ tests, with timing
      run: |
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        RAPIDYAML_TIMED=1 \
        make -C rapidyaml/native cfg
    - name: build c++ tests, with timing
      run: |
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        RAPIDYAML_TIMED=1 \
        make -C rapidyaml/native build
    - name: run c++ tests, with timing
      run: |
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        RAPIDYAML_TIMED=1 \
        make -C rapidyaml/native test

  # run the java tests, also in Debug to test with assertions
  java:
    runs-on: ubuntu-24.04
    if: always()
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
        - bt: Debug
        - bt: Release
    steps:
    - name: checkout (action)
      uses: actions/checkout@v4
      with: {submodules: recursive, fetch-depth: 0} # use fetch-depth to ensure all tags are fetched
    - name: run java tests
      run: |
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        make -C rapidyaml test

  # run core and ys tests, also in Debug to test with assertions
  ys:
    name: ys/${{matrix.ysparser}}/${{matrix.bt}}
    runs-on: ubuntu-24.04
    if: always()
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
        - {ysparser: ryml-evt, bt: Debug}
        - {ysparser: ryml-evt, bt: Release}
        - {ysparser: ryml-edn, bt: Debug}
        - {ysparser: ryml-edn, bt: Release}
    steps:
    - name: checkout (action)
      uses: actions/checkout@v4
      with: {submodules: recursive, fetch-depth: 0} # use fetch-depth to ensure all tags are fetched
    - name: run core tests
      run: |
        . .profile
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        YS_PARSER=${{matrix.ysparser}} \
        make test-core v=1
    - name: run ys tests
      run: |
        . .profile
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        YS_PARSER=${{matrix.ysparser}} \
        make -C ys test-run v=1
    - name: run ys tests ?
      run: |
        . .profile
        RAPIDYAML_BUILD_TYPE=${{matrix.bt}} \
        YS_PARSER=${{matrix.ysparser}} \
        make test-ys v=1   # is this the same as above?
