name: rapidyaml

defaults:
  run:
    shell: bash -xeo pipefail {0}
'on':
  workflow_dispatch: null
  push:
    branches:
    - main
  pull_request:

jobs:

  # check that the spec'ed version of rapidyaml passes its own tests
  ryml:
    runs-on: ubuntu-24.04
    if: always()
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
        - bt: Debug
        - bt: Release
    steps:
    - name: checkout (action)
      uses: actions/checkout@v4
      with: {submodules: recursive, fetch-depth: 0} # use fetch-depth to ensure all tags are fetched
    - name: checkout rapidyaml
      run: |
        cd rapidyaml/native
        make rapidyaml
    - name: configure
      run: |
        cd rapidyaml/native/rapidyaml
        cmake -B build -D CMAKE_BUILD_TYPE=${{matrix.bt}} -D RYML_BUILD_TESTS=ON
    - name: build
      run: |
        cd rapidyaml/native/rapidyaml
        cmake --build build --target ryml-test-build --parallel --verbose
    - name: run tests
      run: |
        cd rapidyaml/native/rapidyaml
        cmake --build build --target ryml-test-run

  # run the c++ tests, also in Debug to test with assertions
  cpp:
    runs-on: ubuntu-24.04
    if: always()
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
        - {bt: Debug, musl: 0}
        - {bt: Debug, musl: 1}
        - {bt: Release, musl: 0}
        - {bt: Release, musl: 1}
    env:
      MKOPTS: RAPIDYAML_BUILD_TYPE=${{matrix.bt}} RAPIDYAML_MUSL=${{matrix.musl}}
    steps:
    - name: checkout (action)
      uses: actions/checkout@v4
      with: {submodules: recursive, fetch-depth: 0} # use fetch-depth to ensure all tags are fetched
    - name: check jni header up to date
      run: make -C rapidyaml/native -B jni jnicheck
    - name: get rapidyaml
      run: make -C rapidyaml/native rapidyaml
    - name: run c++ tests, static -----------------------------
      run: echo
    - name: cfg c++, static
      run: $MKOPTS make -C rapidyaml/native cfg-static
    - name: build c++ tests, static
      run: $MKOPTS make -C rapidyaml/native build-static
    - name: run c++ tests, static
      run: $MKOPTS make -C rapidyaml/native test-static
    - name: run c++ tests, static with timing
      run: $MKOPTS make -C rapidyaml/native test-static-timing
    - name: run c++ tests, shared -----------------------------
      run: echo
    - name: cfg c++, shared
      run: $MKOPTS make -C rapidyaml/native cfg-shared
    - name: build c++ tests, shared
      run: $MKOPTS make -C rapidyaml/native build-shared
    - name: run c++ tests, shared
      run: $MKOPTS make -C rapidyaml/native test-shared
    - name: run c++ tests, shared with timing
      run: $MKOPTS make -C rapidyaml/native test-shared-timing

  # run the java tests, also in Debug to test with assertions
  java:
    runs-on: ubuntu-24.04
    if: always()
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
        - {bt: Debug, musl: 0}
        - {bt: Debug, musl: 1}
        - {bt: Release, musl: 0}
        - {bt: Release, musl: 1}
    env:
      MKOPTS: RAPIDYAML_BUILD_TYPE=${{matrix.bt}} RAPIDYAML_MUSL=${{matrix.musl}}
    steps:
    - name: checkout (action)
      uses: actions/checkout@v4
      with: {submodules: recursive, fetch-depth: 0} # use fetch-depth to ensure all tags are fetched
    - name: build lib
      run: $MKOPTS make -C rapidyaml build
    - name: build jar
      run: $MKOPTS make -C rapidyaml jar
    - name: install
      run: $MKOPTS make -C rapidyaml install
    - name: run java tests
      run: $MKOPTS make -C rapidyaml test
