name: ys

defaults:
  run:
    shell: bash -xeo pipefail {0}
'on':
  workflow_dispatch: null
  push:
    branches:
    - main
  pull_request:

jobs:

  # run ys tests, also in Debug to test with assertions.
  # TODO: add a job to do all the downloads and build graalvm, and
  # then make the other jobs depend on that
  ys:
    name: ys/${{matrix.ysparser}}/${{matrix.bt}}
    runs-on: ubuntu-24.04
    if: always()
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
        - {v: 1, ysparser: snake}
        - {v: 1, ysparser: rapid-arr, bt: Debug}
        - {v: 1, ysparser: rapid-arr, bt: Release}
        - {v: 1, ysparser: rapid-buf, bt: Debug}
        - {v: 1, ysparser: rapid-buf, bt: Release}
    steps:
    - name: checkout (action)
      uses: actions/checkout@v4
      with: {submodules: recursive, fetch-depth: 0} # use fetch-depth to ensure all tags are fetched
    - name: run core tests
      run: |
        . .profile
        make test-core \
            v=${{matrix.v}} \
            YS_TESTING=1 \
            YS_PARSER=${{matrix.ysparser}} \
            RAPIDYAML_BUILD_TYPE=${{matrix.bt}}
    - name: run ys/test-run
      run: |
        . .profile
        make -C ys test-run \
            v=${{matrix.v}} \
            YS_PARSER=${{matrix.ysparser}} \
            RAPIDYAML_BUILD_TYPE=${{matrix.bt}}
    - name: run test-ys
      run: |
        . .profile
        make test-ys \
            v=${{matrix.v}} \
            YS_PARSER=${{matrix.ysparser}} \
            RAPIDYAML_BUILD_TYPE=${{matrix.bt}}
    - name: run all tests
      run: |
        . .profile
        make test \
            v=${{matrix.v}} \
            YS_TESTING=1 \
            YS_PARSER=${{matrix.ysparser}} \
            RAPIDYAML_BUILD_TYPE=${{matrix.bt}}
